destination: docs

page_gen-dirs: true

baseurl: "/jekyll"
page_gen:
  - data: 'paintings'
    template: 'product'
    name: 'title'
    dir: 'paintings'
  - data: 'danse'
    template: 'product'
    name: 'title'
    dir: 'danse'